# syntax=docker/dockerfile:1.4
FROM dev-core:latest

# Install nightly nvim for nvim12.
RUN <<'EOF'
cd $HOME

curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz -O
tar xzf $HOME/nvim-linux-x86_64.tar.gz && rm $HOME/nvim-linux-x86_64.tar.gz

mkdir $HOME/.bin
ln -s $HOME/nvim-linux-x86_64/bin/nvim $HOME/.bin/nvim
EOF

# Setup dotfiles
RUN <<'EOF'
git clone https://github.com/nodech/dotfiles $HOME/dotfiles/

mkdir -p $HOME/.config
cd $HOME/dotfiles

make zsh
make config
make nvim

EOF

# Setup neovim
RUN $HOME/nvim-linux-x86_64/bin/nvim --headless -c 'qall'
RUN cd $HOME/.local/share/nvim/site/pack/core/opt/blink.cmp && cargo build --release

# Patch zshrc with custom script
RUN echo "source $HOME/.zshrc.docker" >> $HOME/.zshrc
COPY zshrc.docker /root/.zshrc.docker

# Install all the agents
RUN <<'EOF'
npm install -g @openai/codex
npm install -g @anthropic-ai/claude-code
npm install -g opencode-ai
EOF

# Final docker setup
LABEL project="nodech-env"

ENV TERM=screen-256color

WORKDIR /work

SHELL ["/bin/zsh", "-c"]
CMD ["/bin/zsh"]
