# syntax=docker/dockerfile:1.4
FROM nodech/dev-core:latest

# Install agent CLIs
RUN <<'EOF'
set -e
npm install -g @anthropic-ai/claude-code
npm cache clean --force

pacman -S --noconfirm \
  openai-codex \
  opencode

pacman -Scc --noconfirm
EOF

# Set up dotfiles
RUN <<'EOF'
set -e
git clone https://github.com/nodech/dotfiles $HOME/dotfiles/

mkdir -p $HOME/.config
cd $HOME/dotfiles
make install

EOF

# Set up Neovim
RUN <<'EOF'
set -e
nvim --headless -c 'qall'

cd $HOME/.local/share/nvim/site/pack/core/opt/blink.cmp
cargo build --release

EOF

# Compile bat themes
RUN bat cache --build

# Patch `.zshrc` with a custom script
COPY zshrc.docker /root/.zshrc.docker.init
RUN echo "source $HOME/.zshrc.docker.init" >> $HOME/.zshrc

ENV TERM=screen-256color
ENV COLORTERM=truecolor

WORKDIR /work

SHELL ["/bin/zsh", "-c"]
CMD ["/bin/zsh"]
