# syntax=docker/dockerfile:1.4
FROM nodech/dev-core:latest

# Install agent CLIs
RUN <<'EOF'
set -e
npm install -g @openai/codex
npm install -g @anthropic-ai/claude-code
npm install -g opencode-ai
npm cache clean --force
EOF

# Install nightly Neovim for Neovim 0.12.
RUN <<'EOF'
set -e
cd $HOME

curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz -O
tar xzf $HOME/nvim-linux-x86_64.tar.gz && rm $HOME/nvim-linux-x86_64.tar.gz

mkdir $HOME/.bin
ln -s $HOME/nvim-linux-x86_64/bin/nvim $HOME/.bin/nvim
EOF

# Set up dotfiles
RUN <<'EOF'
set -e
git clone https://github.com/nodech/dotfiles $HOME/dotfiles/

mkdir -p $HOME/.config
cd $HOME/dotfiles

make zsh
make config
make nvim

EOF

# Set up Neovim
RUN <<'EOF'
set -e
$HOME/nvim-linux-x86_64/bin/nvim --headless -c 'qall'

cd $HOME/.local/share/nvim/site/pack/core/opt/blink.cmp
cargo build --release

EOF

# Compile bat themes
RUN bat cache --build

# Patch `.zshrc` with a custom script
COPY zshrc.docker /root/.zshrc.docker.init
RUN echo "source $HOME/.zshrc.docker.init" >> $HOME/.zshrc

ENV TERM=screen-256color
ENV COLORTERM=truecolor

WORKDIR /work

SHELL ["/bin/zsh", "-c"]
CMD ["/bin/zsh"]
